In [1]:
import numpy as np # Image Processing 
import fitz ,os,glob,cv2,pathlib  # Pdf To Image 
from PIL import Image # For Reading Image (1)
from matplotlib.image import imread # For Reading Image (2)
from sklearn.model_selection import train_test_split #Dividing Data 
from sklearn.ensemble import RandomForestClassifier #ML MODEL

In [2]:
from keras.preprocessing.image import img_to_array,load_img,ImageDataGenerator # For Reading Image (3)

In [3]:
def extract_image(file,name):   #Convert Document To Image 
    pdf = fitz.open(file) #Read File 
    page = pdf.loadPage(0) # Get Page 0 
    pix = page.get_pixmap() # Convert To Pixels 
    pix.save("images/"+ name +".jpg") #Save pixels to Image 
    print(f'image {file} Saved')

In [13]:
files = glob.glob("files/*.pdf") #Getting ALL Files 

In [17]:
files[0]

'files\\&-A-152.9.--.0001.00.pdf'

In [18]:
for i in range(len(files)):
    extract_image(files[i],name="file" + str(i))

image files\&-A-152.9.--.0001.00.pdf Saved
image files\&-A-152.9.--.0002.00.pdf Saved
image files\&-A-152.9.--.0003.00.pdf Saved
image files\&-A-152.9.--.0004.00.pdf Saved
image files\&-A-152.9.--.0005.00.pdf Saved
image files\&-A-152.9.--.0006.00.pdf Saved
image files\&-A-152.9.--.0007.00.pdf Saved
image files\&-A-152.9.--.0008.00.pdf Saved
image files\&-A-152.9.--.0009.00.pdf Saved
image files\&-A-152.9.--.0010.00.pdf Saved
image files\&-A-152.9.--.0011.00.pdf Saved
image files\&-A-152.9.--.0012.00.pdf Saved
image files\&-A-152.9.--.0013.00.pdf Saved
image files\&-A-152.9.--.0014.00.pdf Saved
image files\&-A-152.9.--.0015.00.pdf Saved
image files\&-A-152.9.--.0016.00.pdf Saved
image files\&-A-152.9.--.0017.00.pdf Saved
image files\&-A-152.9.--.0018.00.pdf Saved
image files\&-A-152.9.--.0019.00.pdf Saved
image files\&-A-152.9.--.0020.00.pdf Saved
image files\&-A-152.9.--.0021.00.pdf Saved
image files\&-A-152.9.--.0022.00.pdf Saved
image files\&-A-152.9.--.0023.00.pdf Saved
image files

image files\&-A-152.9.--.0194.00.pdf Saved
image files\&-A-152.9.--.0195.00.pdf Saved
image files\&-A-152.9.--.0196.00.pdf Saved
image files\&-A-152.9.--.0197.00.pdf Saved
image files\&-A-152.9.--.0198.00.pdf Saved
image files\&-A-152.9.--.0199.00.pdf Saved
image files\&-A-152.9.--.0200.00.pdf Saved
image files\&-A-152.9.--.0201.00.pdf Saved
image files\&-A-152.9.--.0202.00.pdf Saved
image files\&-A-152.9.--.0203.00.pdf Saved
image files\&-A-152.9.--.0204.00.pdf Saved
image files\&-A-152.9.--.0205.00.pdf Saved
image files\&-A-152.9.--.0206.00.pdf Saved
image files\&-A-152.9.--.0207.00.pdf Saved
image files\&-A-152.9.--.0208.00.pdf Saved
image files\&-A-152.9.--.0209.00.pdf Saved
image files\&-A-152.9.--.0210.00.pdf Saved
image files\&-A-152.9.--.0211.00.pdf Saved
image files\&-A-152.9.--.0212.00.pdf Saved
image files\&-A-152.9.--.0213.00.pdf Saved
image files\&-A-152.9.--.0214.00.pdf Saved
image files\&-A-152.9.--.0215.00.pdf Saved
image files\&-A-152.9.--.0216.00.pdf Saved
image files

In [4]:
if not os.path.exists("images"):  #Making Seprate Folder where all files saved 
    os.mkdir("images")

In [20]:
images = glob.glob("images/*.jpg")  #Getting ALL Images

In [21]:
print(images[0]) # You Can Check glob functions here 

images\file0.jpg


In [22]:
def resize(image_,shape=(841,596)): # You may Resize if needed 
    image = Image.open(image_)
    image = image.resize(shape)
    return image 

In [23]:
data = [] # Creating empty list to store all data 

In [28]:
test_img = load_img(images[0]) #Choose Random Image , I am Choosing First But You May Choose Any 
arr_img = img_to_array(test_img) # Converting to array
arr_img / 255 # Coverting b/w 0-1

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)

In [29]:
for i in range(len(images)):
    data.append(img_to_array(load_img(images[i])) / 255) #Getting All data to one 
    
    


In [30]:
data = np.array(data) # Making it as numpy array 

C:\Users\PC\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.



In [32]:
data.shape

(294,)

In [33]:
data

array([array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        ...,
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32),
       array([[[0.99607843, 0.99607843, 0.99607843],
        [0.99607843, 0.996078

In [34]:
data[0].shape

(842, 596, 3)

In [36]:
x = data[1].reshape(841,596*3) # Converting Image to a particular shape 

In [37]:
x.shape

(841, 1788)

In [38]:
x

array([[0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       ...,
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843],
       [0.99607843, 0.99607843, 0.99607843, ..., 0.99607843, 0.99607843,
        0.99607843]], dtype=float32)

In [39]:
y = np.ones((841,1788)) # np.ones(size of array ) ones because our all features are true , there is no fake feature

In [40]:
model = RandomForestClassifier() # Preparing model 

In [41]:
model.fit(x,y) #Training Model

RandomForestClassifier()

In [42]:
test =cv2.imread("CE.jpg") # Testing on a random Image 

In [29]:
test.shape

(596, 834, 3)

In [43]:
test  = test.reshape(834,596*3) # Converting Image to a model shape

In [44]:
model.predict(test) # Getting Predictions 

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [45]:
import pickle  # Saving Model with Pickle , i have already saved model 

with open("model.pkl","wb") as f:
    pickle.dump(model,f)

In [47]:
# Load Model as 

import pickle 

model = pickle.load(open("model.pkl",'rb'))